### ISSUE TITLE
UniversalWindowsPlatform

### ISSUE THREAD

**Issue by tvlada73** [100prznt/Rca.EzoDeviceLib#2]
Hi , love your repo, just recive Ezo.Ph and RTD!

Can we go up to UniversalWindowsPlatform ver. 6.2.9?
Also, is there a need for a minimum version of 15063?

Will send you some pull request.

BR

**Comment by 100prznt** [comment]
Hi @tvlada73 ,
I'm glad you like my work.

UWP 6.2.9 is no problem, I updated the package.

The reason for version 15063 is that I am currently using this version on my target systems.
If you can test older versions, I could set the min. version down.

Elias
